### ISSUE TITLE
13z980 觸控板無效

### ISSUE THREAD

**Issue by suzuke** [ShiningXu/LG-Gram-macOS#14]
try this one
https://www.jianshu.com/p/e01c958650fc

把由VoodooI2C开发/技术支持成员Ben Raz修改过的VoodooI2C.kext 和 VoodooI2CHID.kext 放入 系统盘 \Library\Extensions\

_Originally posted by @harrylwc in https://github.com/ShiningXu/LG-Gram-macOS/issues/8#issuecomment-546753590_

抱歉重開issue ，這裡提供的網址已經失效。
請問有其他的連結嗎？或者可以提供一下檔案跟描述一下做法，謝謝

問題描述: 觸控板可識別，但毫無反應

**Comment by Jkfengbo223** [comment]
我一开始也是触控板没反应，昨天试着用了一下最新的2.4版本的VoodooI2，结果几乎完美解决了本人的lg gram13z980的触控板问题，现在单指，多指各项手势功能都正常了，触控板有问题的朋友可以试一试。 
解决方法：用clover configuration挂载EFI分区，下载2.4版VoodooI2C-2.4.zip，解压后只需将包里的VoodooI2C.kext 和 VoodooI2CHID.kext这两个文件放入EFI/clover/kext/other/路径，替换原来旧版的VoodooI2C.kext 和 VoodooI2CHID.kext，再重启笔记本，触控板就可以用了。本人10.15.3系统，亲测有效。  
附VoodooI2C-2.4.zip下载链接：
[https://github.com/alexandred/VoodooI2C/releases](url)

I did n’t respond to the touchpad at the beginning. Yesterday I tried to use the latest 2.4 version of VoodooI2. As a result, I almost solved the problem of my lg gram13z980 ’s touchpad. Now, the gesture function of single finger and multi finger is normal. , Friends who have problems with the touchpad can give it a try.
Solution: Mount the EFI partition with clover configuration, download version 2.4 of VoodooI2C-2.4.zip, and after decompression, simply place the two files VoodooI2C.kext and VoodooI2CHID.kext in the package into the EFI / clover / kext / other / path , Replace the original old version of VoodooI2C.kext and VoodooI2CHID.kext, and then restart the notebook, the touchpad can be used. My 10.15.3. System, pro test is effective.
Here is the download link of  VoodooI2C-2.4.zip:
[https://github.com/alexandred/VoodooI2C/releases](url)

**Comment by suzuke** [comment]
感謝，替換之後就可以使用了。
