### ISSUE TITLE
CPU temperature issue

### ISSUE THREAD

**Issue by Parthvsquare** [ShiningXu/LG-Gram-macOS#15]
I am having my CPU at 3ghz with 60s to 70s when idle 
I tried upgrading kext, also I got help from discord community but that too doesn’t solve the issue

**Comment by suzuke** [comment]
I have made another EFI with opencore and also fixed the trackpad bug.
The brightness fn key is working, and also re-patched the battery dsdt.
I don't not have such cpu issue,  maybe you could give it a try. 
[LG-Gram-13z980](https://github.com/suzuke/LG-Gram-13z980-Opencore)

**Comment by Parthvsquare** [comment]
Will give it a try, also is iMessage working
