### ISSUE TITLE
Any news on having the touchpad working?

### ISSUE THREAD

**Issue by BrunoGM** [ShiningXu/LG-Gram-macOS#17]
Hey, any news about the bug on the touchpad?

**Comment by Parthvsquare** [comment]
Upgrade to latest voodooi2c kext, it is stable-ish
You can replicate most of the gesture with minor hick ups

**Comment by BrunoGM** [comment]
Thanks for the tip, gonna try it out once I install MacOS

**Comment by chnxan** [comment]
it works well

**Comment by BrunoGM** [comment]
I tested it, its running super smoothly with the latest VoodooI2C kext, thanks guys.
