### ISSUE TITLE
请问可以识别摄像头和指纹，但是U盘识别不出来，请问这该如何解决？

### ISSUE THREAD

**Issue by CharleoY** [ShiningXu/LG-Gram-macOS#3]

**Comment by ShiningXu** [comment]
U盘用的是3.0还是2.0？
型号是15寸还是14寸？

**Comment by CharleoY** [comment]
3.0的u 盘，我的是13寸的，端口编号不一致么？

**Comment by ShiningXu** [comment]
[Archive.zip](https://github.com/ShiningXu/LG-Gram-macOS/files/3137339/Archive.zip)
解压后把USBPort.kext 放到/clover/kexts/other下替换掉原来的，两个USB口都试一下。
不行的话需要重新定制。

**Comment by CharleoY** [comment]
嗯。还是不行。我在找找办法。
另外，如何定制？

**Comment by ShiningXu** [comment]
![image](https://user-images.githubusercontent.com/15712567/57067802-98a7b280-6d02-11e9-9332-37dcba96b3dd.png)

在系统报告里看一下，有没有你的U盘
定制USB看这个
https://blog.daliansky.net/Intel-FB-Patcher-tutorial-and-insertion-pose.html

**Comment by CharleoY** [comment]
这个我看了，没有U盘，usb设备 camera和 指纹的sensor，还有外置的无线鼠标接收器，无线网卡都正常工作。

**Comment by CharleoY** [comment]
换了通用的USBinjectall就正常了。谢谢你的帮助

**Comment by ShiningXu** [comment]
USBinjectall 是把所有的USB端口都打开，功耗会大一些。最好还是根据上面那个帖子搞一下。
顺便帮忙star一下哈。
