### ISSUE TITLE
13z980 触控板驱动无效

### ISSUE THREAD

**Issue by ChenNima** [ShiningXu/LG-Gram-macOS#8]
进系统后在系统设置里可以调节触控板设置，但是触控板本身没有响应，移动，手势和点击全都没有反应。请问是需要自己额外patch DSDT之类的操作吗？

**Comment by harrylwc** [comment]
try this one
https://www.jianshu.com/p/e01c958650fc

把由VoodooI2C开发/技术支持成员Ben Raz修改过的VoodooI2C.kext 和 VoodooI2CHID.kext 放入 系统盘 \Library\Extensions\

**Comment by suzuke** [comment]
抱歉重開issue ，這裡提供的網址已經失效。
請問有其他的連結嗎？或者可以提供一下檔案跟描述一下做法，謝謝

> try this one
> https://www.jianshu.com/p/e01c958650fc
> 
> 把由VoodooI2C开发/技术支持成员Ben Raz修改过的VoodooI2C.kext 和 VoodooI2CHID.kext 放入 系统盘 \Library\Extensions\
